[package]
name = "xi-tui"
version = "0.1.0"
authors = ["Corentin Henry <corentinhenry@gmail.com>"]

[features]
yaml = []
yaml_format = []

[dependencies]
clippy = {version = "*", optional = true}
termion = "*"
jsonrpc-core = "*"
serde_json = "*"
log = "0.3"
clap = "2.0"

[dependencies.log4rs]
version = "0.4.8"
features = ["yaml"]
